apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-remoteCallService
spec:
  type: git
  params: 
  - name: url
    value: https://github.com/0ht/remoteCallService.git
  - name: revision
    value: master
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: image
spec:
  type: image
  params: 
  - name: url
    value: https://index.docker.io/ohtom/trykaniko
