apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git
spec:
  type: git
  params: 
  - name: url
    value: https://github.com/0ht/remoteCallService
  - name: revision
    value: master